#!/bin/sh

# Consoom better

alias yt='ytfzf -t'

alias yd=yt-dlp
alias ytmp3ch='yt-dlp --extract-audio --audio-format mp3 --split-chapters --no-check-certificate'
alias ytmp3='yt-dlp --extract-audio --audio-format mp3 '
alias ytmp4='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"'
alias ytmp4low='yt-dlp -f "bestvideo[height<=480]+bestaudio/best[height<=480]"'
alias ytplaylist='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" -ciw -o "%(title)s.%(ext)s" -v '
alias ytlist="yt-dlp --write-sub -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' "

#PACMAN & YAY

alias ps='sudo pacman -S'
alias pss='sudo pacman -Ss'
alias psyu='sudo pacman -Syu'
alias psyyu='sudo pacman -Syyu'

alias pr='sudo pacman -R'
alias prns='sudo pacman -Rns'

alias pr='sudo pacman -R'

alias y=yay
alias ys='yay --noconfirm -S '
alias ysyu='yay -Syu'
alias yi='yay -P --stats'

# Files Stuff
alias mf=touch
alias md=mkdir
alias o=xdg-open

# git
alias commit='git commit -m'
alias push='git push origin master'
alias gc='git clone'

# Programs
alias n=nvim
alias ls=lsd 
alias f=lfrun


alias whichkey="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'\""

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"


# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias nf=neofetch
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -h' # show sizes in MB

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias listsystemd="systemctl list-unit-files --state=enabled"
alias s="systemctl"

# cloud
alias encrypt="gpg -c --no-symkey-cache --cipher-algo AES256"
alias decrypt="gpg" 

# PDF Manipulation
alias topdf="soffice --headless --convert-to pdf"

# Chumma 
alias busy="genact"

alias p3="python3"

alias ffs="bspc wm -r"
alias fgs="setxkbmap -option altwin:swap_alt_win,ctrl:swapcaps"
alias cfg='/usr/bin/git --git-dir=$HOME/.DOTs/ --work-tree=$HOME'

alias randompassword='tr -dc "a-zA-Z0-9_#@.-" < /dev/urandom | head -c 14 | xclip -selection clipboard'

alias theo='ssh root@theosoc.org'

alias dict='cambrinary -w'
