#!/bin/sh

# Taskwarrior
alias t=task
alias tui=taskwarrior-tui
tp() {
  task project:"$1"
}
alias tn='clear;task next'
alias ts='clear;task summary'
alias ta='task add'
alias tan='task add scheduled:today'
alias tat='task add scheduled:tomorrow until:sch+14d'
alias tm='task modify'
alias trol="task sch:yes status:pending modify sch:tod"
alias td='clear;task next +ACTIVE or +OVERDUE or due:today or scheduled:today or pri:H; calcurse -r; timew | grep -v "no active time"'
alias tal='task add dep:"$(task +LATEST uuids)"'

#GPUs
alias gputest='glxinfo | grep "OpenGL renderer"'
alias fanauto=' nbfc set -f 0 -a && nbfc set -f 1 -a'
alias fanoff=' nbfc set -f 0 -s 0 && nbfc set -f 1 -s 0'
alias fanfull=' nbfc set -f 0 -s 100 && nbfc set -f 1 -s 100'

# Consoom better
alias D='dust .'
alias M='mpv .'
alias yt='ytfzf -t'

alias yw='yt-dlp -S "ext:webm:webm" '
alias yd=yt-dlp
alias ytmp3ch='yt-dlp --extract-audio --audio-format mp3 --split-chapters --no-check-certificate'
alias ytmp3='yt-dlp --extract-audio --audio-format mp3 '
alias ytmp4='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"'
alias ytmp4low='yt-dlp -f "bestvideo[height<=480]+bestaudio/best[height<=480]"'
alias yt360='yt-dlp -f "bestvideo[height<=360]+bestaudio/best[height<=360]"'
alias ytplaylist='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" -ciw -o "%(title)s.%(ext)s" -v '
alias ytlist="yt-dlp --write-sub -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' "
alias ytlow="yt-dlp -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' --embed-subs --merge-output-format mkv"
alias ytlm="yt-dlp -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' --embed-subs --merge-output-format mkv -o '%(playlist_index)s-%(title)s.%(ext)s' "
alias ytlffs="yt-dlp -f 'bestvideo[height<=360]+bestaudio/best[height<=360]' --embed-subs --merge-output-format mkv -o '%(playlist_index)s-%(title)s.%(ext)s' "

#PACMAN & YAY

alias pss='sudo pacman -S'
alias psyu='sudo pacman -Syu'
alias psyyu='sudo pacman -Syyu'

alias pr='sudo pacman -R'
alias prns='sudo pacman -Rns'

alias pr='sudo pacman -R'

alias y=yay
alias ys='yay --noconfirm -S '
alias ysyu='yay -Syu'
alias yi='yay -P --stats'

# Files Stuff
alias mf=touch
alias md=mkdir
alias v=nvim
alias o=xdg-open

# git
alias gm='git commit -m'
alias gp='git push -u origin main'
alias gc='git clone'
alias gl='git pull'
alias gs='git status'
alias ga='git add .'
alias gk='git checkout'


# Programs
alias n=node

alias g=ghci
alias ci='cabal init'
alias cb='cabal build'
alias cr='cabal run'
alias cg='cabal repl'

alias gw='ghci -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-import-lists'
alias ls=lsd 
alias f=lfrun


alias whichkey="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'\""

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"


# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias nf=neofetch
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -h' # show sizes in MB

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias listsystemd="systemctl list-unit-files --state=enabled"
alias s="systemctl"

# cloud
alias encrypt="gpg -c --no-symkey-cache --cipher-algo AES256"
alias decrypt="gpg" 

# PDF Manipulation
alias topdf="soffice --headless --convert-to pdf"

# Chumma 
alias busy="genact"

alias p3="python3"

alias ffs="bspc wm -r"
alias fgs="setxkbmap -option altwin:swap_alt_win,ctrl:swapcaps"
alias cfg='/usr/bin/git --git-dir=$HOME/.DOTs/ --work-tree=$HOME'

alias randompassword='tr -dc "a-zA-Z0-9_#@.-" < /dev/urandom | head -c 14 | xclip -selection clipboard'

alias theo='ssh root@theosoc.org'

alias dict='cambrinary -w'
alias sg='sudo gparted'
# Go
alias gr="go run"
alias gb="go build"
alias gd="go doc"
alias arthur="yt-dlp -f \"bestvideo[height<=360]+bestaudio/best[height<=480]\" --embed-chapters --embed-subs --merge-output-format mkv \"https://www.youtube.com/watch?v=Yat0ZKduW18&list=PL9GwT4_YRZdBf9nIUHs0zjrnUVl-KBNSM\""


# pandoc 🐐

alias html2pdf="pandoc -s --toc -o out.pdf --pdf-engine=pdflatex --variable=geometry:"top=20pt,bottom=20pt,left=20pt,right=20pt" " 


jv() {
  f=$1
  f2=${f%.*}
  trap "/bin/rm -f $f2.class" 
  javac $1
  java $f2
  /bin/rm -f $f2.class
}

ch() {
  file=$1
  file_name=${file%.*}
  mcs $file
  mono $file_name.exe
  rm -f $file_name.exe
}

