#!/bin/zsh
bspc rule -r "*"

# wal -i ~/.wallpapers/athens.jpeg &
wal -i ~/Pictures/Wallpapers/athens.jpeg
. $HOME/.xprofile
. $HOME/.cache/wal/colors.sh
$HOME/.config/polybar/launch.sh &
# fusuma &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color6"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 12
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config window_gap 5

###---Rules---###
bspc rule -a Zathura state=tiled
bspc rule -a discord desktop=^5
bspc rule -a Emacs state=tiled


