#! /bin/sh
bspc rule -r "*"

sxhkd &
clipmenud &
wal -i ~/Pictures/Wallpapers/athens.jpeg &
$HOME/.config/polybar/launch.sh &
systemctl --user enable pipewire.service &
systemctl --user enable pipewire-pulse.service &
systemctl --user enable pipewire-media-session.service &

. $HOME/.xprofile
. $HOME/.cache/wal/colors.sh

bspc monitor -d 1 2 3 4 5HOME 6

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color6"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 12
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config window_gap 3

###---Rules---###
bspc rule -a Zathura state=tiled
bspc rule -a discord desktop=^5

